name: FACT

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - sympy
  - tqdm
  - requests
  - pyyaml
  - joblib
  - networkx
  - filelock
  - loguru
  - packaging
  - pillow
  - fonttools
  - freetype
  - ffmpeg
  - qt6-main
  - pyside6
  - pip:
      - torch-geometric==2.7.0
      - psutil
      - gdown
      - xxhash
      - aiohttp
      - psutil
      - pynvml
      - codecarbon
